name: Deploy to Cloud Foundry
on:
  push:
    branches:
    - main
jobs:
    Data:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Use Node.js
          uses: actions/setup-node@v1
          with:
            node-version: 16

        - name: ECHO
          run: |
            echo ${{ github.event.inputs }}
            echo ${{ vars.TMS_URL }}
            echo '${{ vars.TMS_URL }}/v2/nodes/upload'
