name: Deploy to Cloud Foundry
on:
  push:
    branches:
    - main

  workflow_dispatch:
    inputs:
      tms:
        description: 'SAP BTP Transport Management'        
        default: true
        required: false
        
jobs:
    Data:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Use Node.js
          uses: actions/setup-node@v1
          with:
            node-version: 16

        - name: ECHO
          run: |
            echo ${{ github.event.inputs.tms }}
            echo ${{ github.event.head_commit.message }}
            echo ${{ github.event.changes.body.from }}
            echo ${{ vars.TMS_URL }}
            echo '${{ vars.TMS_URL }}/v2/nodes/upload'

        - name: TMS Upload/Import
          if: ${{ inputs.tms == 'true' }}
          run: |  
            echo ${{ inputs.tms }}
